services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir backend_API backend_API.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4